### ISSUE TITLE
window环境裁剪+字幕报错

### ISSUE THREAD

**Issue by iosplist** [alibaba-damo-academy/FunClip#36]
Traceback (most recent call last):
  File "D:\anaconda3\envs\funclip\lib\site-packages\gradio\queueing.py", line 527, in process_events
    response = await route_utils.call_process_api(
  File "D:\anaconda3\envs\funclip\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\anaconda3\envs\funclip\lib\site-packages\gradio\blocks.py", line 1847, in process_api
    result = await self.call_function(
  File "D:\anaconda3\envs\funclip\lib\site-packages\gradio\blocks.py", line 1433, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\anaconda3\envs\funclip\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\anaconda3\envs\funclip\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "D:\anaconda3\envs\funclip\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\anaconda3\envs\funclip\lib\site-packages\gradio\utils.py", line 805, in wrapper
    response = f(*args, **kwargs)
  File "F:\ai\FunClip\funclip\launch.py", line 82, in video_clip_addsub
    return audio_clipper.video_clip(
  File "F:\ai\FunClip\funclip\videoclipper.py", line 237, in video_clip
    os.makedirs(output_dir, exist_ok=True)
  File "D:\anaconda3\envs\funclip\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: ' '

**Comment by R1ckShi** [comment]
https://github.com/alibaba-damo-academy/FunClip/discussions/47
