### ISSUE TITLE
安装时候找不到文件

### ISSUE THREAD

**Issue by pigesky2024** [alibaba-damo-academy/FunClip#44]
Traceback (most recent call last):
  File "E:\剪辑筛选\funclip\launch.py", line 6, in <module>
    funasr_model = AutoModel(model="iic/speech_seaco_paraformer_large_asr_nat-zh-cn-16k-common-vocab8404-pytorch",
  File "E:\剪辑筛选\env\lib\site-packages\funasr\auto\auto_model.py", line 137, in __init__
    spk_model, spk_kwargs = self.build_model(**spk_kwargs)
  File "E:\剪辑筛选\env\lib\site-packages\funasr\auto\auto_model.py", line 158, in build_model
    kwargs = download_model(**kwargs)
  File "E:\剪辑筛选\env\lib\site-packages\funasr\download\download_from_hub.py", line 11, in download_model
    kwargs = download_from_ms(**kwargs)
  File "E:\剪辑筛选\env\lib\site-packages\funasr\download\download_from_hub.py", line 79, in download_from_ms
    install_requirements(requirements)
  File "E:\剪辑筛选\env\lib\site-packages\funasr\utils\install_model_requirements.py", line 21, in install_requirements
    result = subprocess.run(
  File "E:\剪辑筛选\env\lib\subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "E:\剪辑筛选\env\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "E:\剪辑筛选\env\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] 系统找不到指定的文件。
Press any key to continue . . .

**Comment by R1ckShi** [comment]
应该是你的python没有pip，funasr在"funasr\utils\install_model_requirements.py", line 21处调用的是pip来安装他的requirements
可以搜索下在你的系统环境中安装pip的方法

**Comment by JackeyLiu000** [comment]
WARNING:root:Initializing VideoClipper.
Traceback (most recent call last):
  File "C:\Users\Administrator\FunClip\funclip\launch.py", line 124, in <module>
    theme = gr.Theme.load("funclip/utils/theme.json")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\gradio\themes\base.py", line 139, in load
    with open(path) as fp:
         ^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'funclip/utils/theme.json'



我遇到的是这个问题，代码小白，在本地搭环境，不知道如何处理，求棒棒忙

**Comment by R1ckShi** [comment]
> WARNING:root:Initializing VideoClipper. Traceback (most recent call last): File "C:\Users\Administrator\FunClip\funclip\launch.py", line 124, in theme = gr.Theme.load("funclip/utils/theme.json") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python311\Lib\site-packages\gradio\themes\base.py", line 139, in load with open(path) as fp: ^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'funclip/utils/theme.json'
> 
> 我遇到的是这个问题，代码小白，在本地搭环境，不知道如何处理，求棒棒忙

你需要在Funclip目录下运行这个程序`python funclip/launch.py`，可以在命令行输入ls，看funclip目录是不是在当前路径下

**Comment by R1ckShi** [comment]
> WARNING:root:Initializing VideoClipper. Traceback (most recent call last): File "C:\Users\Administrator\FunClip\funclip\launch.py", line 124, in theme = gr.Theme.load("funclip/utils/theme.json") ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Python311\Lib\site-packages\gradio\themes\base.py", line 139, in load with open(path) as fp: ^^^^^^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'funclip/utils/theme.json'
> 
> 我遇到的是这个问题，代码小白，在本地搭环境，不知道如何处理，求棒棒忙

参考一下这个哈 https://www.zhihu.com/question/588872249/answer/3500713424
