### ISSUE TITLE
这个是需要配置openai账号吗

### ISSUE THREAD

**Issue by mqxqls** [alibaba-damo-academy/FunClip#46]
这个错误不太懂

Traceback (most recent call last):
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpcore/_sync/http_proxy.py", line 207, in handle_request
    return self._connection.handle_request(proxy_request)
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpcore/_sync/http11.py", line 238, in _receive_event
    raise RemoteProtocolError(msg)
httpcore.RemoteProtocolError: Server disconnected without sending a response.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xqls/app/FunClip/funclip/launch.py", line 251, in <module>
    funclip_service.launch()
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/gradio/blocks.py", line 2324, in launch
    httpx.get(
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpx/_api.py", line 198, in get
    return request(
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpx/_api.py", line 106, in request
    return client.request(
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpx/_client.py", line 827, in request
    return self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 232, in handle_request
    with map_httpcore_exceptions():
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/xqls/app/FunClip/venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: Server disconnected without sending a response.

**Comment by R1ckShi** [comment]
是的，使用gpt系列模型需要您有openai的账号并且有余额，把api-key配置到对应的位置，用于体验的话可以使用g4f开头的那个模型，他使用了https://github.com/xtekky/gpt4free仓库来免费调用gpt
另外您也可以使用阿里云百炼的apikey来调用qwen系列模型，方法是一样的
