### ISSUE TITLE
出现[WinError 3]并不是config_defaults.py没有配置好,原因不得而解。

### ISSUE THREAD

**Issue by 851543** [alibaba-damo-academy/FunClip#61]
Traceback (most recent call last):
  File "D:\Python\Python310\lib\site-packages\gradio\queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
  File "D:\Python\Python310\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Python\Python310\lib\site-packages\gradio\blocks.py", line 1908, in process_api
    result = await self.call_function(
  File "D:\Python\Python310\lib\site-packages\gradio\blocks.py", line 1485, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "D:\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\Python\Python310\lib\site-packages\gradio\utils.py", line 808, in wrapper
    response = f(*args, **kwargs)
  File "E:\FunASR\FunClip\funclip\launch.py", line 86, in video_clip_addsub
    return audio_clipper.video_clip(
  File "E:\FunASR\FunClip\funclip\videoclipper.py", line 246, in video_clip
    os.makedirs(output_dir, exist_ok=True)
  File "D:\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [WinError 3] 系统找不到指定的路径。: ' '
Keyboard interruption in main thread... closing server.

**Comment by 851543** [comment]
我想知道到底是哪里出现问题了 [WinError 3] 和 [WinError 2] 有差别。

**Comment by 851543** [comment]
点击裁剪+字幕会出现这个报错，并且我尝试在文件输出路径给 E:\FunASR\temp 会出现这个问题Traceback (most recent call last):
  File "D:\Python\Python310\lib\site-packages\gradio\queueing.py", line 528, in process_events
    response = await route_utils.call_process_api(
  File "D:\Python\Python310\lib\site-packages\gradio\route_utils.py", line 270, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\Python\Python310\lib\site-packages\gradio\blocks.py", line 1908, in process_api
    result = await self.call_function(
  File "D:\Python\Python310\lib\site-packages\gradio\blocks.py", line 1485, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Python\Python310\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 2144, in run_sync_in_worker_thread
    return await future
  File "D:\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\Python\Python310\lib\site-packages\gradio\utils.py", line 808, in wrapper
    response = f(*args, **kwargs)
  File "E:\FunASR\FunClip\funclip\launch.py", line 86, in video_clip_addsub
    return audio_clipper.video_clip(
  File "E:\FunASR\FunClip\funclip\videoclipper.py", line 246, in video_clip
    os.makedirs(output_dir, exist_ok=True)
  File "D:\Python\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "D:\Python\Python310\lib\os.py", line 215, in makedirs
    makedirs(head, exist_ok=exist_ok)
  File "D:\Python\Python310\lib\os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [WinError 123] 文件名、目录名或卷标语法不正确。: ' E:'

**Comment by 851543** [comment]
我尝试在文件输出路径给C:\Users\阿俊\AppData\Local\Temp\gradio 与项目上传文件同级，并不会发生错误，并能够生效了，这个是什么原理。额外问一个可以修改实例的视频和音频以及上传视频和音频的目录位置吗? 这些东西占取我硬盘内存。

**Comment by R1ckShi** [comment]
刚修复了一个小bug，这个bug可能曾导致windows下裁剪+字幕功能异常
另外使用裁剪+字幕功能依赖于imagemagick，并且moviepy库需要能够找到imagemagick的安装位置，参考https://github.com/alibaba-damo-academy/FunClip/discussions/47

**Comment by 851543** [comment]
> 刚修复了一个小bug，这个bug可能曾导致windows下裁剪+字幕功能异常 另外使用裁剪+字幕功能依赖于imagemagick，并且moviepy库需要能够找到imagemagick的安装位置，参考#47

确实最新的版本解决了windows下裁剪+字幕功能异常，也就是我提出问题的FileNotFoundError: [WinError 3] 系统找不到指定的路径。: ' '错误。
